spring:
  datasource:
    url: jdbc:h2:file:~/data/desafiotest
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  h2:
    console:
      path: /h2-console
      enabled: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create-drop