spring:
  data:
    # Configuração de Paginação
    web:
      pageable:
        default-page-size: 10
        max-page-size: 30
  datasource:
    url: jdbc:postgresql://localhost:5432/backend_api
    username: postgres
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc.lob.non_contextual_creation: true